### PR TITLE
about page is done

### PR DESCRIPTION
**Pull request by dnanjunda**

### CODE REVIEW

**Comment by jayrc7** [comment]
Danielle has requested some changes in the about page, I'll talk more on that tomorrow.

**Comment by jayrc7** [comment]
merge master into your branch but move your page content inside of anshul's dummy pages

**Review by jayrc7 — CHANGES_REQUESTED** [review]
image

It looks great, just one tiny change. Can you increase the width of the container holding everything so that the about us header gets displayed in one line only and so that the picture has more width since it looks a little crammed right now. Thanks man

**Comment by jayrc7** [comment]
as a temporary change, i've decreased the font size of the header text while Dhanush will be looking for a way to increase the container width.

**Review by jayrc7 — DISMISSED** [review]
looks great

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Screen Shot 2020-05-20 at 9 38 08 PM
It seems to look really smushed together when the window is at half the width. You might want to make  use of more of the white space in the left part of the screen, and just make your font smaller and use the extra space to make your image a bit more proportional. Using vw or even vh might be a good idea!

**Comment by jayrc7** [comment]
image

The header is still breaking into two lines, try increasing the width of the container and decrease padding if you have any.

**Comment by jayrc7** [comment]
NOW WE'RE TALKING DHANUSH less go, merge master into your branch again and it's good to go

**Review by jayrc7 — APPROVED** [review]
great job Dhanush!

**Pull request merged**
