### PR TITLE
finished WaysToGive

### PR DESCRIPTION
**Pull request by nvanny**

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Screen Shot 2020-05-20 at 9 19 58 PM
So this happens when I enter an invalid amount/don't add anything. You'll have to readjust the height/weight requirements put on the error icon.

**Comment by jayrc7** [comment]
also can you merge master onto your branch, and move your page onto the dummy page that anshul set up for it, thanks Nico

**Review by jayrc7 — CHANGES_REQUESTED** [review]
image

it looks pretty good! one thing though can you lower the error icon so that it's centered with the text field and button?

**Comment by jayrc7** [comment]
Nice nice it looks pretty good! once you merge master it should be good to go.

**Review by jayrc7 — APPROVED** [review]

**Pull request merged**
