### PR TITLE
Mailchimp newsletter

### PR DESCRIPTION
**Pull request by nvanny**

### CODE REVIEW

**Comment by nvanny** [comment]
For the home page, the slideshow arrows appear over the modal and z-index isn't working.

**Comment by Amrit-S** [comment]
I had that problem too when I was doing the Footer. Just adjust the z-index of the modal to around 10, and it should work.

**Comment by Amrit-S** [comment]
Also, make sure that your position type is anything but static (the default type). I think you need relative position or something to use z-index

**Review by jayrc7 — CHANGES_REQUESTED** [review]
It looks good but needs some adjusting. The footer is too long vertically for mobile devices. Also, remove some of the spacing between the subscribe text and the form. 

image

**Review by jayrc7 — CHANGES_REQUESTED** [review]
Mobile looks good, for ipads can you please decrease the size of it so that it doesn't take up the whole screen 
image

**Review by jayrc7 — APPROVED** [review]
Awesome thanks Nico!

**Pull request merged**
