### PR TITLE
global css file is done

### PR DESCRIPTION
**Pull request by dnanjunda**

### CODE REVIEW

**Comment by jayrc7** [comment]
The structure looks good, howcome h1 and p don't have font sizes? Also, none of the pages are importing the global.css file

**Comment by dnanjunda** [comment]
> The structure looks good, howcome h1 and p don't have font sizes? Also, none of the pages are importing the global.css file

Some pages use h1 for header and others use it for regular paragraphs, which is why I can't include font sizes. Same with p.

**Comment by jayrc7** [comment]
I see, in that case it's better to make all h1's and p's the same. That way all the text for the different pages are consistent. Right now the text looks different between all the pages in the dropdown, support page, and audition page.

**Review by jayrc7 — CHANGES_REQUESTED** [review]
Please refer to the comment above, also I tried changing all h1 text color to blue and h2 text to yellow and the website didn't update. Once setting global css rules, inside each pages css file remove the rules that were overlapped like text color that way changing global css can actually update the website.

**Review by jayrc7 — CHANGES_REQUESTED** [review]
A couple of changes should be added: 
- when changing the h1 text color to blue, the header for the directors, support, and audition pages did not change color. 
- Have every text paragraph in the website use the paragraph tag (<.p>) for consistency.

**Review by jayrc7 — APPROVED** [review]
Well done! Thanks a lot Dhanush

**Pull request merged**
