### PR TITLE
New navbar and global css merges have been done

### PR DESCRIPTION
**Pull request by Anshul-Birla**

### CODE REVIEW

**Review by jayrc7 — CHANGES_REQUESTED** [review]
It works really well, but the navbar's css looks a little funny when the window takes up half of my screen. Would it be possible to still show the links and not the hamburger icon when the window takes up half of a screen? 

image

**Comment by jayrc7** [comment]
It works great! I did notice the refreshing but i don't believe it's something to be worried about. Danielle and the designer agreed to not have a contact page anymore, can you remove that please. Also, now when the screen reaches halfway, can you still include the social media icons? Try to place them below the logo or maybe decrease the navbar size to make space for them. 

image

**Review by jayrc7 — APPROVED** [review]
looks great

**Review by Amrit-S — APPROVED** [review]
Looks really good Anshul! Small thing - I think "Auditions" is supposed to be "Audition" based off of what Jessica gave.

**Pull request merged**
