### PR TITLE
Final Icons (without modal code)

### PR DESCRIPTION
**Pull request by TheHiddenLayer**

### CODE REVIEW

**Comment by jayrc7** [comment]
Almost good to go. When a link is clicked it should open a new tab instead. Add target="_blank" to each link

**Review by jayrc7 — CHANGES_REQUESTED** [review]
refer to comment above

**Review by jayrc7 — APPROVED** [review]
nice job dude!

**Review by Anshul-Birla — APPROVED** [review]
Good stuff

**Pull request merged**
