### PR TITLE
mobile-about-page

### PR DESCRIPTION
**Pull request by dnanjunda**
Ready to merge changes for mobile about page to master

### CODE REVIEW

**Review by Anshul-Birla — APPROVED** [review]
looks gucci

**Review by Anshul-Birla — DISMISSED** [review]
Looks good

**Comment by jayrc7** [comment]
Great job Dhanush it looks really good on mobile but it has the moblie css applied on fullscreen
image

**Review by jayrc7 — CHANGES_REQUESTED** [review]
refer to above comment

**Review by jayrc7 — APPROVED** [review]
looks good Dhanush!

**Review by Anshul-Birla — APPROVED** [review]
Gj

**Pull request merged**
