### PR TITLE
mobile css for contact page is done. MERGE THIS ONE 

### PR DESCRIPTION
**Pull request by Anshul-Birla**

### CODE REVIEW

**Review by jayrc7 — CHANGES_REQUESTED** [review]
Nice progress! Here's what it looks like on my end. 
image

It looks great but it doesn't look like how it does on the reference video that's pinned on the slack channel. 

image

Sorry if it's too small my video player didn't want to go full screen.

**Comment by Anshul-Birla** [comment]
> It looks great but it doesn't look like how it does on the reference video that's pinned on the slack channel.
 
Oh yeah i forgot about the mobile version renders I'll finish it tomorrow shouldn't be too hard to do

**Review by jayrc7 — APPROVED** [review]
nice nice

**Review by TheHiddenLayer — APPROVED** [review]
go ahead

**Pull request merged**
