### PR TITLE
Support Page - Mobile + PayPal

### PR DESCRIPTION
**Pull request by Amrit-S**
Breakdown of Changes:

PayPal.js: Basically allows the PayPal button to render on the screen, and implements some basic logistic details (order customization, amount, popping alert after successful transaction).

SupportMain.js: Renders everything text related on the screen + the Donate Button

SupportStates.js: Activates once DonateButton is pressed. Switches the donate button out for the "donation process" (choosing an amount, then going to the PayPal button with option to adjust)

Support.css: Layout is different for <= 600 && >600 so I need to be adjusting quite a few things. Some of them are just there to negate the effects from the >600 layout.

### CODE REVIEW

**Comment by jayrc7** [comment]
It looks really good Amrit! If you can raise everything a bit higher it would definitely look better. Also add a couple of <[br /]>  (without the brackets) at the end of the file so that there's a little bit of whitespace in between the button and the bottom of the page. 
image

**Review by jayrc7 — CHANGES_REQUESTED** [review]
refer to comment above

**Review by jayrc7 — CHANGES_REQUESTED** [review]
There is some overflow going on horizontally meaning I can scroll from left to right, can you add this in the Support page css
body {
      overflow-x: hidden;
}

and see if that fixes the issue?

**Review by Anshul-Birla — DISMISSED** [review]
Good stuff!

**Review by jayrc7 — APPROVED** [review]
Looks good Amrit!

**Review by Anshul-Birla — APPROVED** [review]
Gj

**Pull request merged**
