### PR TITLE
Gallery Page

### PR DESCRIPTION
**Pull request by jayrc7**

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Jason, the page looks really good! Two small things.

In mobile desktop, your sentence is being cut off for Video Gallery.

And then for one of the iPad sizes, the text for the video gallery is really small. 

Screen Shot 2020-06-29 at 8 53 56 PM
Screen Shot 2020-06-29 at 8 53 30 PM

**Review by Amrit-S — APPROVED** [review]
Looks great!

**Comment by nvanny** [comment]
For the mobile version, the gallery took a long time to load initially for me, but was fine after that.  I'm not entirely sure how big of an issue this is but that's what I had.  Otherwise, everything else looks pretty good, no noticeable bugs to me.

**Review by TheHiddenLayer — APPROVED** [review]
Looks good. Like others I also experienced a slow load time but it should be fine.

**Comment by Amrit-S** [comment]
Nico and Upo, can you guys comment on how long the gallery page took to load for you? Initial render on my laptop never took more than 3-4 seconds for me, so I wasn't aware of this. If possible, can you link footage or something?
@nvanny @ubhattac

**Comment by jayrc7** [comment]
Slow loading of the gallery page will be addressed in a future pr. @nvanny @ubhattac @Amrit-S

**Pull request merged**
